import { ProjectData } from "@/types/projects";
import { ServiceType } from "@/types/services";

export const ILLUSTRATION_PROJECTS = [
  {
    name: "Presentación privada medica",
    country: "USA",
    description:
      "Ilustración y styleframe para video del cuidado en la tercer edad",
    folderName: "presentacion-privada-medica",
    gridType: "onetwoonefour",
    imageQuantity: 8,
  },
  {
    name: "Primal",
    country: "Argentina",
    description: "Diseño de personaje y muñeco textil",
    folderName: "primal",
    gridType: "onetwoonetwotwo",
    imageQuantity: 13,
  },
  {
    name: "Roedores y dinosaurios",
    country: "España",
    description: "Creación de arte conceptual",
    folderName: "roedores-y-dinosaurios",
    gridType: "onetwoonefour",
    imageQuantity: 9,
  },
  {
    name: "Personajes de fantasía",
    country: "España",
    description: "Diseño de personajes",
    folderName: "personajes-de-fantasia",
    gridType: "onetwoonetwotwo-wide",
    imageQuantity: 9,
  },
  {
    name: "Illuminated",
    country: "USA",
    description: "Illuminated Alphabet",
    folderName: "illuminated",
    gridType: "oneonefourtwo",
    imageQuantity: 32,
  },
  {
    name: "Mudarse",
    country: "España",
    description: "Ilustracion nuevos lugares proyecto personal",
    folderName: "mudarse",
    gridType: "one",
    imageQuantity: 6,
  },
  {
    name: "Alfabeto",
    country: "Argentina",
    description: "Alphabet challenge",
    folderName: "alfabeto",
    gridType: "four",
    imageQuantity: 25,
  },
  {
    name: "Colección rosa",
    country: "Argentina",
    description: "Colección ilustradas",
    folderName: "coleccion-rosa",
    gridType: "threeonetwoone",
    imageQuantity: 7,
  },
  {
    name: "Colección de ilustraciones",
    country: "Argentina",
    description: "Ilustraciones personales",
    folderName: "coleccion-de-ilustraciones",
    gridType: "oneonefourtwo",
    imageQuantity: 12,
  },
];

export const ANIMATION_PROJECTS = [
  {
    name: "Shutterfly",
    description: "Storyboad, styleframes e ilustración para Shutterfly",
    country: "USA",
    folderName: "shutterfly",
    gridType: "onetwoonefour",
    imageQuantity: 4,
    videoUrl: "https://www.youtube.com/embed/-CrREZtdzSg?si=LT_ZLkrNOaXP_jR1",
  },
  {
    name: "Tatari TV",
    description: "Ilustraciones para videos de Tatari TV",
    country: "USA",
    folderName: "tatari",
    gridType: "onetwoonetwotwo-wide",
    imageQuantity: 6,
    videoUrl: "https://www.youtube.com/embed/9XAO7arAqDs?si=FZTp__f9yT5k9ZbF",
  },
  {
    name: "Linmore Led",
    description: "Storyboad, styleframes y dirección de arte para Linmore Led",
    country: "USA",
    folderName: "linmore-led",
    gridType: "oneonefourtwo",
    imageQuantity: 6,
    videoUrl: "https://www.youtube.com/embed/QzvengrRdeE?si=kmL4kNP4Z3aSYads",
  },
  {
    name: "Bridge Tech Medical",
    description:
      "Project Manager, Dirección de arte, storyboard, styleframe e Illustración",
    country: "USA",
    folderName: "bridge-tech-medical",
    gridType: "two-wide",
    imageQuantity: 7,
    videoUrl: "https://www.youtube.com/embed/4YQ9MxZjfNc?si=LWHP4VJ_jKyVM23F",
  },
  {
    name: "NEHA",
    description: "Ilustraciones para NEHA",
    country: "USA",
    folderName: "neha",
    gridType: "onetwoonetwotwo-wide",
    imageQuantity: 11,
    videoUrl: "https://www.youtube.com/embed/oZ95wQ6mv_Q?si=9heo3QMCpuw9dKvf",
  },
  {
    name: "UK School",
    description:
      "Creación de personajes, storyboard, styleframe,animación y dirección creativa",
    country: "UK",
    folderName: "uk-school",
    gridType: "one",
    imageQuantity: 3,
    hasVideo: true,
  },
  {
    name: "Continental refining company",
    description:
      "Dirección de arte e Ilustración para Continental refining company - CRC",
    country: "USA",
    folderName: "crc",
    gridType: "onetwoonefour",
    imageQuantity: 13,
    videoUrl: "https://www.youtube.com/embed/PVBrrZ4a9xM?si=Mf8nS-REGmdPaUGK",
  },
  {
    name: "Hum Capital",
    description:
      "Project Manager, dirección de arte, storyboard ilustración para Hum Capital",
    country: "USA",
    folderName: "hum-capital",
    gridType: "two-wide",
    imageQuantity: 5,
    videoUrl: "https://www.youtube.com/embed/N6zFFBg4J7U?si=BdOnC0J8-FjmJEow",
  },
  {
    name: "Zion",
    description:
      "Dirección de arte, ilustraciones y animación para app de video game Zion",
    country: "España",
    folderName: "zion",
    gridType: "onetwoonetwotwo-wide",
    imageQuantity: 6,
  },
  {
    name: "ADEvantage",
    description:
      "Styleframes, ilustraciones y dirección de arte para ADEvantage",
    country: "USA",
    folderName: "adevantage",
    gridType: "one",
    imageQuantity: 2,
    videoUrl: "https://www.youtube.com/embed/HsJshXSRYds?si=Q9naCzpgqtUFPsNX",
  },
  {
    name: "OQSIE",
    description: "Project Manager, Dirección de arte, storyboard",
    country: "USA",
    folderName: "oqsie",
    gridType: "one-wide",
    imageQuantity: 1,
    hasVideo: true,
    videoUrl: "https://www.youtube.com/embed/155itTgk1t0?si=-VwA6GCbHNPNi5kI",
  },
  {
    name: "TDVerse",
    description: "Styleframes e ilustración para TDVerse",
    country: "USA",
    folderName: "tdverse",
    gridType: "onetwoonetwotwo-wide",
    imageQuantity: 9,
  },
];

const EDITORIAL_PROJECTS = [
  {
    name: "Primal",
    country: "España",
    description: "Novela gráfica",
    folderName: "primal",
    gridType: "three",
    imageQuantity: 6,
  },
  {
    name: "Ajuntamente de Barcelona",
    country: "España",
    description:
      "Propuesta de campaña publicitaria para el Ayuntamiento de Barcelona",
    folderName: "ajuntamente-de-barcelona",
    gridType: "onetwoonetwotwo-wide",
    imageQuantity: 11,
  },
  {
    name: "Birdwatchers",
    country: "España",
    description: "Libro de colorear para adultos",
    folderName: "birdwatchers",
    gridType: "one-wide",
    imageQuantity: 5,
  },
  {
    name: "Tinta",
    country: "Argentina",
    description: "Revista ilustración y cultura latinoamericana",
    folderName: "tinta",
    gridType: "one-wide",
    imageQuantity: 18,
  },
  {
    name: "Timo",
    country: "Alemania",
    description: "Libro COVID-19",
    folderName: "timo",
    gridType: "oneonethreetwothree",
    imageQuantity: 10,
    hasVideo: true,
  },
  {
    name: "Autismo Avila",
    country: "España",
    description: "Ilustraciones editoriales",
    folderName: "autismo-avila",
    gridType: "one",
    imageQuantity: 4,
  },
];

const SOCIAL_MEDIA_PROJECTS = [
  {
    name: "Claire Salabelle",
    country: "Argentina",
    description: "Creación de piezas de redes sociales",
    folderName: "claire-salabelle",
    gridType: "onetwoonetwotwo",
    imageQuantity: 4,
    hasVideo: true,
    hasSecondVideo: true,
  },
  {
    name: "Proyecto Personal",
    country: "España",
    description: "Realización de GIFs y piezas para redes sociales",
    folderName: "proyecto-personal",
  },
  {
    name: "Momentful App",
    country: "UK",
    description:
      "Ilustración y conceptualización de E-Cards (Tarjetas electrónicas ilustradas)",
    folderName: "momentful-app",
    gridType: "one-wide",
    imageQuantity: 7,
  },
  {
    name: "Social Media",
    country: "Argentina",
    description: "Creaciones de Piezas para redes sociales",
    folderName: "social-media",
    gridType: "two",
    imageQuantity: 6,
  },
  {
    name: "Trippin' Store",
    country: "Argentina",
    description: "Creaciones de Piezas para redes sociales",
    folderName: "trippin-store",
    gridType: "two",
    imageQuantity: 4,
    hasVideo: true,
    hasSecondVideo: true,
  },
  {
    name: "BW Animations",
    country: "España",
    description:
      "Animación frame by frame de personajes para proyecto personal",
    folderName: "bw-animations",
  },
];

const BRANDING_PROJECTS = [
  {
    name: "Bardo",
    country: "España",
    description: "Branding y posts de RRSS",
    folderName: "bardo",
    gridType: "one-wide",
    imageQuantity: 6,
  },
  {
    name: "Viuty",
    country: "España",
    description: "Rediseño de branding y post de RRSS",
    folderName: "viuty",
    gridType: "two",
    imageQuantity: 28,
  },
  {
    name: "Malcriada",
    country: "Argentina",
    description: "Brand refresh",
    folderName: "malcriada",
    gridType: "oneonethreetwothree",
    imageQuantity: 10,
  },
  {
    name: "Baba Studio",
    country: "España",
    description:
      "Logo - Identidad Visual - Catalogo - Etiquetas - Redes Sociales",
    folderName: "baba-studio",
    gridType: "oneonefourtwo",
    imageQuantity: 8,
  },
  {
    name: "Harmony",
    country: "Colombia",
    description:
      "Creación de packaging de una línea de productos dermatológicos.",
    folderName: "harmony",
    gridType: "onetwoonefour",
    imageQuantity: 9,
  },
  {
    name: "Logofolio",
    country: "",
    description: "Desarrollo de logos para diferentes marcas",
    folderName: "logofolio",
    gridType: "one",
    imageQuantity: 10,
  },
  {
    name: "Iamskin",
    country: "España",
    description: "Diseño grafico, RRSS, fotografia, edicion de video",
    folderName: "iamskin",
    gridType: "one",
    imageQuantity: 5,
  },
  {
    name: "Desquiciado",
    country: "Argentina",
    description: "Ilustracion para etiqueta",
    folderName: "desquiciado",
    gridType: "onetwoonetwotwo",
    imageQuantity: 6,
  },
  {
    name: "Fig creme",
    country: "Argentina",
    description: "Ilustración cientifica packaging",
    folderName: "fig-creme",
    gridType: "onetwoonetwotwo",
    imageQuantity: 8,
  },
];

export const PROJECTS: Record<string, ProjectData[]> = {
  [ServiceType.ILLUSTRATION]: ILLUSTRATION_PROJECTS,
  [ServiceType.ANIMATION]: ANIMATION_PROJECTS,
  [ServiceType.EDITORIAL]: EDITORIAL_PROJECTS,
  [ServiceType.SOCIAL_MEDIA]: SOCIAL_MEDIA_PROJECTS,
  [ServiceType.BRANDING]: BRANDING_PROJECTS,
  [ServiceType.MOTION_GRAPHICS]: [],
};
